apiVersion: apps/v1
kind: Deployment
metadata:
  name: upm-app-deployment
  labels:
    app: upm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upm-app
  template:
    metadata:
      labels:
        app: upm-app
    spec:
      containers:
        - name: upm-app-container
          image: neeharikasingh/upm-app:0.4
          ports:
            - containerPort: 8088
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: upm-app-configmap
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: upm-app-configmap
                  key: db_port
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: upm-app-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: upm-app-secret
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: upm-app-configmap
                  key: db_name