apiVersion: apps/v1
kind: Deployment
metadata:
  name: wss-app-deployment
  labels:
    app: wss-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wss-app
  template:
    metadata:
      labels:
        app: wss-app
    spec:
      containers:
        - name: wss-app-container
          image: neeharikasingh/wss-app:0.5
          ports:
            - containerPort: 8090
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: postgres_port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: postgres_db
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wss-app-secret
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wss-app-secret
                  key: postgres_password
            - name: PRODUCT_EVENT
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: product_event
            - name: PRICE_EVENT
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: price_event
            - name: NOTIFICATION_EVENT
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: notification_event
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: wss-app-configmap
                  key: kafka_server
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wss-app-secret
                  key: kafka_username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wss-app-secret
                  key: kafka_password